FROM centos:latest

MAINTAINER NewstarCorporation

RUN  yum install httpd -y

COPY files /var/www/html/

COPY img  /var/www/html/

COPY ic.png /var/www/html/

COPY index.html /var/www/html/

CMD [“/usr/sbin/httpd”, “-D”, “FOREGROUND”]

EXPOSE 80
