FROM ubuntu:latest

MAINTAINER NewstarCorporation

COPY files /var/www/html/

COPY img  /var/www/html/

COPY ic.png /var/www/html/

COPY index.html /var/www/html/

RUN /bin/sh -c  apt-get install -y apache2

CMD ["apach2" "start"]

EXPOSE 80
