FROM ubuntu:latest

MAINTAINER NewstarCorporation

WORKDIR /usr/share/nginx/html

COPY files /usr/share/nginx/html

COPY img  /usr/share/nginx/html

COPY ic.png /usr/share/nginx/html

COPY index.html /usr/share/nginx/html

RUN apt-get update

CMD ["/bin/sh"]

CMD ["nginx" "-g" "daemon]

ENTRYPOINT ["nginx" "-g" "daemon]

EXPOSE 80
